### ISSUE TITLE
Skipped Layers w/ PLA

### ISSUE THREAD

**Issue by hokiespurs** [FRF-Remote-Sensing/FRF_Ultimaker2#1]
Having issues with skipped layers/bed drop using blue PLA  

The skipped Z layers make a very weak part.

Let's try adding grease to see if it's a bed level issue.
If that doesn't fix it, it could be under-extrusion... so we can try to clean out any gunk from the printer head.

**Comment by hokiespurs** [comment]
Issue appears to be due to underextrusion.

"Atomic Method" was done and the head seemed clean.

Problem appears to be from "Feeder Skips", as described here:
https://ultimaker.com/en/community/view/15998-feeder-skips-back-every-couple-of-seconds

Temperature was increased to 230 degrees. It seemed to have less skipping.  Unsure if this solved problem completely.

**Comment by njspore** [comment]
Sounds like some of the community recommends vegetable oil for lubricant and report better success.  I also found the link to the file for the alternative feeder assembly.  I've read that many have even more success using this alternate design as it attempts to minimize friction which can cause filament binding and under-extrusion.  Check out the links:

Persistent under-extrusion thread: https://ultimaker.com/en/general-discussion/view/8737-persistent-under-extrusion-problem?page=1

Alternative Feeder Assembly: https://www.youmagine.com/designs/alternative-um2-feeder-version-two

**Comment by hokiespurs** [comment]
Nick and I received great technical support from Joseph (joseph@fbrc8.com)

We replaced the temperature sensor, and the brass nozzle.  This appears to have solved the problem!! Joseph believes that the temperature sensor was bad, and we were printing with an insufficient temperature.  

The test cylinder was able to print up to the 10mm^3/s with only minor underextrusion on the 9 and 10mm^3 layers.
